In [3]:
# run this cell (maybe twice to get %matplotlib notebook to work)
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
from microphone import record_audio
from typing import Tuple
from typing import Union, Tuple, Sequence
from pathlib import Path
import os
%matplotlib notebook

In [4]:
def getFiles() -> Sequence[str]:
    path = Path.cwd() / "data"
    music = os.listdir(path)
    array = [os.path.join(path,item) for item in music if item[-4:]==".mp3"]
    return array


In [5]:
array = getFiles()

['/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/tolerate.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/crime.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/gold.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/champagne.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/damn.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/happiness.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/cowboy.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/evermore.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/ivy.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/willow.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/marjorie.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/dorothea.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/closure.mp3',
 '/Users/shiftyblock/Documents/GitHub/ryan-sus/audio/data/coney.mp3',


In [7]:
import librosa

#takes in an array of file paths and outputs librosa audio info
def toAudio(array: Sequence[str]) -> Sequence[Tuple[np.ndarray, int]]:
    audios = []
    for item in array:
        recorded, rate = librosa.load(item, sr =44100, mono = True)
        audios.append((recorded, rate))
    return audios
# `audios` is a numpy array of N audio samples

audios = toAudio(array)

/Users/shiftyblock/opt/anaconda3/envs/week1/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
/Users/shiftyblock/opt/anaconda3/envs/week1/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
/Users/shiftyblock/opt/anaconda3/envs/week1/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
/Users/shiftyblock/opt/anaconda3/envs/week1/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
/Users/shiftyblock/opt/anaconda3/envs/week1/lib/python3.8/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
/Users/shiftyblock/opt/anaconda3/envs/week1/lib/py

In [8]:
audios

[(array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7207936e-06,  2.6061334e-05,  1.9037490e-05], dtype=float32),
  44100),
 (array([ 1.47622850e-05,  1.36683075e-05, -1.86741563e-05, ...,
         -3.73592375e-05, -2.87156672e-05, -3.14706049e-05], dtype=float32),
  44100),
 (array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 44100),
 (array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 44100),
 (array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 44100),
 (array([-2.9409373e-05, -4.5361860e-05,  1.1832793e-05, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32),
  44100),
 (array([1.61434527e-05, 1.31561565e-05, 1.88286031e-05, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00], dtype=float32),
  44100),
 (array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 44100),
 (array([2.8692750e-05, 6.4643289e-05, 5.4227032e-05, ..., 4.3473989e-05,
         2.3386052e-05, 1.1289971e-05], dtype=float32),
  44100),
 (array([0., 0., 0

In [19]:
import matplotlib.mlab as mlab

#takes in an audio tuple(audio, sampling rate)
#outputs a tuple of log10spectrogram, frequencies, and times
def toSpectrogram(audio: Tuple[np.ndarray, int]) -> Sequence[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    recorded_audio = audio[0]
    sampling_rate = audio[1]
    S, freqs, times = mlab.specgram(
        recorded_audio,
        NFFT=4096,
        Fs=sampling_rate,
        window=mlab.window_hanning,
        noverlap=int(4096 / 2)
    )
    S = np.clip(S, 1e-20, None)
    S = np.log10(S)
    return ((S,freqs,times))

In [20]:
specgrams = toSpectrogram(audios)

In [21]:
pickle = np.array(specgrams, dtype = object)
with open('specgrams.npy', 'wb') as f:
    np.save(f, pickle)

In [22]:
#To load the numpy file
'''
with open('specgrams.npy', 'rb') as f:
    specgrams = np.load(f, allow_pickle = True)
'''

"\nwith open('specgrams.npy', 'rb') as f:\n    specgrams = np.load(f, allow_pickle = True)\n"